//
//  ojibwayFirstViewController.h
//  Ojibway
//
//  Created by Darrick Baxter on 12-05-13.
//  Copyright (c) 2012 Ogoki Learning Systems Inc. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <AudioToolbox/AudioToolbox.h>

@interface ojibwayFirstViewController : UIViewController {

    IBOutlet UIScrollView *scrollother;
    IBOutlet UIScrollView *scrolllanguages;
    IBOutlet UIScrollView *scrollactions;
    IBOutlet UIScrollView *scrollanimal;
    IBOutlet UIScrollView *scrollbounce;
    IBOutlet UIScrollView *scrollipad;
}

-(IBAction)givewater;
-(IBAction)goodbye;
-(IBAction)Hello;
-(IBAction)mynameis;
-(IBAction)No;
-(IBAction)Thankyou;
-(IBAction)Yes;
-(IBAction)allday;
-(IBAction)allnight;
-(IBAction)badweather;
-(IBAction)beautifulday;
-(IBAction)blackclouds;
-(IBAction)cloudy;
-(IBAction)cold;
-(IBAction)ice;
-(IBAction)raining;
-(IBAction)snowing;
-(IBAction)startingrain;
-(IBAction)stopraining;
-(IBAction)strongwind;
-(IBAction)sunshining;
-(IBAction)thundering;
-(IBAction)Arms;
-(IBAction)Ears;
-(IBAction)Eyes;
-(IBAction)Feet;
-(IBAction)Hands;
-(IBAction)Head;
-(IBAction)Legs;
-(IBAction)Stomach;
-(IBAction)Arrives;
-(IBAction)Arrivesrunning;
-(IBAction)Before;
-(IBAction)Begin;
-(IBAction)Blames;
-(IBAction)Changeit;
-(IBAction)Coverupwithblanket;
-(IBAction)Crying;
-(IBAction)deaddied;
-(IBAction)Eat;
-(IBAction)Letsgo;
-(IBAction)Loving;
-(IBAction)Reads;
-(IBAction)Running;
-(IBAction)Says;
-(IBAction)Sing;
-(IBAction)Sitdown;
-(IBAction)Sitstill;
-(IBAction)Standup;
-(IBAction)Wait;
-(IBAction)Wakeup;
-(IBAction)Walk;
-(IBAction)Birthday;
-(IBAction)Boy;
-(IBAction)Child;
-(IBAction)Children;
-(IBAction)Girl;
-(IBAction)Grandfather;
-(IBAction)Man;
-(IBAction)Married;
-(IBAction)Mydaughter;
-(IBAction)Myfather;
-(IBAction)Mygrandmother;
-(IBAction)Mymother;
-(IBAction)Myson;
-(IBAction)Mysons;
-(IBAction)Women;
-(IBAction)Yourdaughter;
-(IBAction)Yourfather;
-(IBAction)Yourmother;
-(IBAction)Yourson;
-(IBAction)Areyouhealthy;
-(IBAction)Areyousick;
-(IBAction)Ask;
-(IBAction)Askhimher;
-(IBAction)Howareyoudoing;
-(IBAction)Howareyoufeeling;
-(IBAction)What;
-(IBAction)whatareyoudoing;
-(IBAction)Whatishappening;
-(IBAction)Whatisyourname;
-(IBAction)Abandonhimherbyrunningoff;
-(IBAction)Almost;
-(IBAction)Already;
-(IBAction)Badbreath;
-(IBAction)Believehimher;
-(IBAction)Come;
-(IBAction)Comein;
-(IBAction)Dependson;
-(IBAction)Dont;
-(IBAction)Dreaming;
-(IBAction)Feedme;
-(IBAction)Gohome;
-(IBAction)Gotosleep;
-(IBAction)Helpme;
-(IBAction)HeShecandoit;
-(IBAction)Hurryup;
-(IBAction)Iamgoingtocallyourmother;
-(IBAction)Imgoingtotellonyou;
-(IBAction)Iamhomealone;
-(IBAction)Iamhungry;
-(IBAction)Iamshy;
-(IBAction)Iamsleepy;
-(IBAction)Iamtired;
-(IBAction)Iloveyou;
-(IBAction)Keepquiet;
-(IBAction)Letsgofishing;
-(IBAction)Lookout;
-(IBAction)sheheiscold;
-(IBAction)sheheishot;
-(IBAction)Thatsenough;
-(IBAction)Theyarelaughing;
-(IBAction)Youareloud;
-(IBAction)Bear;
-(IBAction)Beaver;
-(IBAction)Bee;
-(IBAction)Bird;
-(IBAction)Birds;
-(IBAction)Buffalo;
-(IBAction)Bug;
-(IBAction)Cow;
-(IBAction)Crow;
-(IBAction)Deer;
-(IBAction)Dogs;
-(IBAction)Duck;
-(IBAction)Eagle;
-(IBAction)Fish;
-(IBAction)Fox;
-(IBAction)Goose;
-(IBAction)Horse;
-(IBAction)Mosquito;
-(IBAction)Muskrat;
-(IBAction)Pig;
-(IBAction)Rabbit;
-(IBAction)Skunk;
-(IBAction)smallCat;
-(IBAction)Snake;
-(IBAction)Turtle;
-(IBAction)Wolf;
-(IBAction)Apple;
-(IBAction)bacon;
-(IBAction)Bakesomebread;
-(IBAction)Food;
-(IBAction)GreaseLard;
-(IBAction)Raspberries;
-(IBAction)Raspberry;
-(IBAction)Strawberry;
-(IBAction)Acrossthewater;
-(IBAction)East;
-(IBAction)Lake;
-(IBAction)North;
-(IBAction)Northernlights;
-(IBAction)Road;
-(IBAction)South;
-(IBAction)West;
-(IBAction)Automobile;
-(IBAction)Axe;
-(IBAction)boat;
-(IBAction)Earth;
-(IBAction)House;
-(IBAction)money;
-(IBAction)Tree;
-(IBAction)BadMedicine;
-(IBAction)Medicine;
-(IBAction)Saskatoons;
-(IBAction)Tobacco;
-(IBAction)Water;
-(IBAction)Eight;
-(IBAction)Five;
-(IBAction)Four;
-(IBAction)Nine;
-(IBAction)One;
-(IBAction)Seven;
-(IBAction)Six;
-(IBAction)Ten;
-(IBAction)Three;
-(IBAction)Two;



@end
